application: russel-watsky-website
module: default
api_version: 1
runtime: python27
threadsafe: yes
version: 0

handlers:

- url: /(.*\.webp)
  mime_type: image/webp

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^source$